export default {
    APPOINTMENT_MODAL: 'APPOINTMENT_MODAL',
    HOW_TO_CHOOSE_PSY_MODAL: 'HOW_TO_CHOOSE_PSY_MODAL',
    CRITERIA_PSY_MODAL: 'CRITERIA_PSY_MODAL',
    RANDOM_PSY_MODAL: 'RANDOM_PSY_MODAL',
    HELP_MODAL: 'HELP_MODAL',
}